#!/bin/sh

bspc rule -r "*"
xsetroot -cursor_name left_ptr &
$HOME/.local/bin/bspwm/monitordetect

## Basics
bspc config border_width		2
bspc config window_gap			20
bspc config split_ratio			0.5
bspc config single_monocle		false
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_follows_pointer	true

## Colours
bspc config normal_border_color		"#383C4A"
bspc config focused_border_color	"#84927D"

## Workspace and Window Rules
bspc rule -a Zathura state=tiled

st -c scratchterm -e tmuxdd &
bspc rule -a scratchterm sticky=on state=floating hidden=on

#dropdownname="dropdown"
#bspc query -N -n .hidden >/dev/null || setsid $TERMINAL -n "$dropdownname" -e dropdown >/dev/null 2>&1 &
#bspc rule -a St:$dropdownname hidden=on
#bspc rule -a St:$dropdownname sticky=on
#bspc rule -a St:$dropdownname state=floating
